name: pull request
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - run: |
          rustup --version
          rustup show
          cargo --version
          cargo +nightly fmt --version
          cargo clippy --version
      - run: cargo +nightly fmt --all -- --check
      - run: cargo clippy --locked --workspace --all-features --all-targets -- -D warnings
